---
- name: A few basic filters
  hosts: localhost
  gather_facts: no

  vars:
    jarlist: [1,1,1,1,1,5]
    repeatlist: [1,2,2,2,4,4,4,4,9,9,9,9]
    repeat2list: [5,5,5,5,5,6,7]
    complexlist: [6,7,8,[9,10,22],87]

  tasks:
  # Produce a list union
  - name: Produce a list union from two lists
    debug:
      msg: 'Display the union of the lists {{ repeatlist|union(repeat2list) }}'

  - name: Jinja2 default filter - example
    debug:
      msg: "Prevent undefined var err {{ myvariable.lower() | default('by setting a default') }}"
    vars:
      myvariable: ""


  - name: create some test users
    user:
      name: "{{ item }}"
      state: present
      groups: "student"
    with_sequence: start=0 end=20 stride=5 
    become: True


